#---------------------------------------------------------------------
# GitHub Action Workflow Basics
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------

# Название экшена
name: My-GitHubActions-Basics

# Создание глобальных переменных
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"
  
# Когда запускать экшен при обновления main
on: 
  push:
    branches: 
      - main

# Создаем задачи
jobs:

  linux_version:
    runs-on: ubuntu-latest  
    steps:
    - name: Verion Linux
      run: cat /etc/os-release
      
# Название первой задачи
  my_testing:
  
  # На чем запускать
    runs-on: ubuntu-latest  
    
    # Шаги задачи
    steps:    
    
    # Вывести на экран "Hello World from Testing job"
     - name: Print Hello Message in Testing
       run : echo "Hello World from Testing job"
    
    # Запуск несколких команд в на одном шаге
     - name: Execure few commands
       run : |
         echo "Hello Message1"
         echo "Hello Message2"
         echo "Appication name: ${{ env.APPLICATION_NAME }}"  # Вывод глобальной переменной   APPLICATION_NAME 
     
     # Копировать файлы репозитория 
     - name: Git clone my repo
       uses: actions/checkout@v1      

# Показать файлы в контейнере образа
     - name: List current folder
       run : ls -la

# Название второй задачи
  my_deploy:
    # На чем запускать
    runs-on: ubuntu-latest  
    
    # Запускать после выполнения задачи my_testing
    needs: [my_testing]    
    
    # Создание локальных переменных
    env:
      VAR1 : "This is Job Level Variable1"
      VAR2 : "This is Job Lebel Variable2"
    
   # Шаги задачи
    steps:
   
   # Вывести на экран "Hello World from Deploy job"
    - name: Print Hello Message in Deploy
      run : echo "Hello World from Deploy job"
      
    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
        
        # Создание переменной только для шагов не глобальный
      env:
        LOCAL_VAR: "This is Super local Environment variable"      

# Deplyo pakcage name is DEPLOY_PACKAGE_NAME (Номер коммита)
    - name: Printing Deployment package
      run : echo "Deplyo pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
      # Узнать версию aws в контейнере 
    - name: Lets test some packages if they are here 1
      run : aws --version
      
      # Узнать версию zip в контейнере 
    - name: Lets test some packages if they are here 2
      run : zip --version      
      
